// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeGestao.Data;

#nullable disable

namespace SistemaDeGestao.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20250509143747_WhatsappBOT3")]
    partial class WhatsappBOT3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaDeGestao.Models.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EstoqueAtual")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoAdicionalId")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoPorProduto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoAdicionalId");

                    b.ToTable("Adicionais");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Complemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EstoqueAtual")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoComplementoId")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoPorProduto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoComplementoId");

                    b.ToTable("Complementos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.DiasFuncionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Domingo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Quarta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Quinta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sabado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Segunda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sexta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Terca")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("DiasFuncionamento");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<int>("DiasFuncionamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("HorarioAbertura")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HorarioFechamento")
                        .HasColumnType("time(6)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("longtext");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiasFuncionamentoId");

                    b.HasIndex("RestauranteId")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.EnderecoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EnderecosEntregas");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.FinalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FinalUsers");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.GrupoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LimiteSelecao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("GrupoAdicionais");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.GrupoComplemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("QuantidadeMaxima")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeMinima")
                        .HasColumnType("int");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("GrupoComplementos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ItemPedidoOpcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemPedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoOpcao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemPedidoId");

                    b.ToTable("ItemPedidoOpcao");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ModeloMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ModelosMensagem");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EnderecoEntregaId")
                        .HasColumnType("int");

                    b.Property<int?>("FinalUserId")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("FinalUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FinalUserTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeDaLoja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoEntregaId");

                    b.HasIndex("FinalUserId");

                    b.HasIndex("PagamentoId")
                        .IsUnique();

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.PedidoCancelado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoReembolso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCancelamento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstaReembolsado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FinalUserId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCancelamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("TransacaoReembolsoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorReembolsado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("FinalUserId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidosCancelados");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.PedidoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PagamentoAprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxaEntrega")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PedidoPagamento");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.PedidoPendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PedidoJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PedidosPendentes");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("ImagemPrincipalUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LojaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoAdicional", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("AdicionalId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoPorProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoAdicional")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProdutoId", "AdicionalId");

                    b.HasIndex("AdicionalId");

                    b.ToTable("ProdutoAdicionais");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoComplemento", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("ComplementoId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoPorProduto")
                        .HasColumnType("int");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ProdutoId", "ComplementoId");

                    b.HasIndex("ComplementoId");

                    b.ToTable("ProdutoComplementos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoGrupoAdicional", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoAdicionalId")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "GrupoAdicionalId");

                    b.HasIndex("GrupoAdicionalId");

                    b.ToTable("ProdutoGrupoAdicional");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoGrupoComplemento", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoComplementoId")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "GrupoComplementoId");

                    b.HasIndex("GrupoComplementoId");

                    b.ToTable("ProdutosGruposComplementos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaLoja")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("refreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.RestauranteCredencialMercadoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId")
                        .IsUnique();

                    b.ToTable("RestauranteCredenciaisMercadoPago");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Adicional", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.GrupoAdicional", null)
                        .WithMany("Adicionais")
                        .HasForeignKey("GrupoAdicionalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Categoria", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithMany("Categorias")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Complemento", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.GrupoComplemento", "GrupoComplemento")
                        .WithMany("Complementos")
                        .HasForeignKey("GrupoComplementoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GrupoComplemento");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Empresa", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.DiasFuncionamento", "DiasFuncionamento")
                        .WithMany()
                        .HasForeignKey("DiasFuncionamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithOne("Empresa")
                        .HasForeignKey("SistemaDeGestao.Models.Empresa", "RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiasFuncionamento");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.GrupoAdicional", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.GrupoComplemento", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ItemPedido", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ItemPedidoOpcao", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.ItemPedido", "ItemPedido")
                        .WithMany("OpcoesExtras")
                        .HasForeignKey("ItemPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemPedido");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Pedido", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.EnderecoEntrega", "EnderecoEntrega")
                        .WithMany()
                        .HasForeignKey("EnderecoEntregaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaDeGestao.Models.FinalUser", "FinalUser")
                        .WithMany("Pedidos")
                        .HasForeignKey("FinalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaDeGestao.Models.PedidoPagamento", "Pagamento")
                        .WithOne("Pedido")
                        .HasForeignKey("SistemaDeGestao.Models.Pedido", "PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnderecoEntrega");

                    b.Navigation("FinalUser");

                    b.Navigation("Pagamento");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.PedidoCancelado", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.FinalUser", "FinalUser")
                        .WithMany()
                        .HasForeignKey("FinalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalUser");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Produto", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithMany("Produtos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoAdicional", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Adicional", "Adicional")
                        .WithMany("Produtos")
                        .HasForeignKey("AdicionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Produto", "Produto")
                        .WithMany("Adicionais")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adicional");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoComplemento", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Complemento", "Complemento")
                        .WithMany("Produtos")
                        .HasForeignKey("ComplementoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Produto", "Produto")
                        .WithMany("Complementos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complemento");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoGrupoAdicional", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.GrupoAdicional", "GrupoAdicional")
                        .WithMany("ProdutosGruposAdicionais")
                        .HasForeignKey("GrupoAdicionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Produto", "Produto")
                        .WithMany("ProdutosGruposAdicionais")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoAdicional");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ProdutoGrupoComplemento", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.GrupoComplemento", "GrupoComplemento")
                        .WithMany("ProdutosGruposComplementos")
                        .HasForeignKey("GrupoComplementoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestao.Models.Produto", "Produto")
                        .WithMany("ProdutosGruposComplementos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoComplemento");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.RestauranteCredencialMercadoPago", b =>
                {
                    b.HasOne("SistemaDeGestao.Models.Restaurante", "Restaurante")
                        .WithOne("CredencialMercadoPago")
                        .HasForeignKey("SistemaDeGestao.Models.RestauranteCredencialMercadoPago", "RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Adicional", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Complemento", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.FinalUser", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.GrupoAdicional", b =>
                {
                    b.Navigation("Adicionais");

                    b.Navigation("ProdutosGruposAdicionais");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.GrupoComplemento", b =>
                {
                    b.Navigation("Complementos");

                    b.Navigation("ProdutosGruposComplementos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.ItemPedido", b =>
                {
                    b.Navigation("OpcoesExtras");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.PedidoPagamento", b =>
                {
                    b.Navigation("Pedido")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Produto", b =>
                {
                    b.Navigation("Adicionais");

                    b.Navigation("Complementos");

                    b.Navigation("ProdutosGruposAdicionais");

                    b.Navigation("ProdutosGruposComplementos");
                });

            modelBuilder.Entity("SistemaDeGestao.Models.Restaurante", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("CredencialMercadoPago")
                        .IsRequired();

                    b.Navigation("Empresa")
                        .IsRequired();

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
